language: php

php:
  - '7.2'
  - '7.3'

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

before_script:
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest


notifications:
  email: false